rabbitmq:
         address: linux6-1:5672
         username: admin
         password: 123456
         virtualHost: /
spring:
       rabbitmq:
                host: linux6-1
                port: 5672
                username: admin
                password: 123456
                virtualHost: /
