spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/rooster?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
